#!/bin/sh
# judge/setup.sh — fetch the problem data this board judges against.
#
#   sh judge/setup.sh [problem ...]        (default: unionfind)
#
# Library Checker's problems live in a separate repository and their test cases
# are GENERATED, not committed: each problem carries generators, a verifier, a
# checker, and the author's own solution, and `generate.py` compiles and runs
# them. That is why this repo holds no .in/.out files — they are reproducible
# from a pinned upstream, and 20 MB of generated bytes in git would make the
# diff of a solution unreadable.
#
# Requirements (upstream's, not ours): python3 and a C++17 compiler.
#
# LC_DIR says where the clone lives; the default sits beside this repo so that
# a fresh checkout of both needs no configuration.
set -eu

here="$(cd "$(dirname "$0")/.." && pwd)"
LC_DIR="${LC_DIR:-$(dirname "$here")/library-checker-problems}"
UPSTREAM=https://github.com/yosupo06/library-checker-problems.git

if [ ! -d "$LC_DIR" ]; then
  echo "setup: cloning $UPSTREAM -> $LC_DIR"
  git clone --depth 1 "$UPSTREAM" "$LC_DIR"
else
  echo "setup: using $LC_DIR"
fi

command -v python3 >/dev/null 2>&1 || { echo "setup: python3 is required" >&2; exit 2; }

for p in "${@:-unionfind}"; do
  echo "setup: generating test cases for $p"
  (cd "$LC_DIR" && python3 ./generate.py -p "$p")
done

echo
echo "setup: done. Now:"
echo "  MERE=<mere checkout> LC_DIR=$LC_DIR python3 judge/run.py"
