#!/bin/sh
# judge/setup.sh — fetch the problem data this board judges against.
#
#   sh judge/setup.sh [problem ...]        (default: unionfind)
#
# Library Checker's problems live in a separate repository and their test cases
# are GENERATED, not committed: each problem carries generators, a verifier, a
# checker, and the author's own solution, and `generate.py` compiles and runs
# them. That is why this repo holds no .in/.out files — they are reproducible
# from a pinned upstream, and 20 MB of generated bytes in git would make the
# diff of a solution unreadable.
#
# THE PIN IS THE POINT, and it used to be a claim rather than a check: this
# script said "a pinned upstream" and then ran `git clone --depth 1` with no
# revision, so it took whatever HEAD was that day. Everything the board reports
# comes from upstream — the time limit, the test data, and the reference
# solution both columns of `ref` are measured from — so an upstream that moves
# moves the measurement, and `--depth 1` leaves no way to go back and look. A
# pin is not how you freeze a number; it is how you can keep asking the same
# question.
#
# LC_REV overrides it, for deliberately asking the question against a newer
# upstream. Then record the answer next to the revision it came from.
#
# Requirements (upstream's, not ours): python3 and a C++17 compiler.
#
# LC_DIR says where the clone lives; the default sits beside this repo so that
# a fresh checkout of both needs no configuration.
set -eu

here="$(cd "$(dirname "$0")/.." && pwd)"
LC_DIR="${LC_DIR:-$(dirname "$here")/library-checker-problems}"
UPSTREAM=https://github.com/yosupo06/library-checker-problems.git
# The revision every number in README.md was measured against.
LC_REV="${LC_REV:-e64660561a995c357cdc61ddee1bde68b80528db}"

if [ ! -d "$LC_DIR" ]; then
  echo "setup: fetching $UPSTREAM @ $LC_REV -> $LC_DIR"
  # fetch-by-revision rather than clone-then-checkout: a shallow clone brings
  # one commit and it is the wrong one, and a full clone to reach a pin is
  # 200 MB to throw away.
  git init -q "$LC_DIR"
  git -C "$LC_DIR" remote add origin "$UPSTREAM"
  git -C "$LC_DIR" fetch -q --depth 1 origin "$LC_REV"
  git -C "$LC_DIR" checkout -q --detach FETCH_HEAD
else
  have="$(git -C "$LC_DIR" rev-parse HEAD 2>/dev/null || echo unknown)"
  if [ "$have" != "$LC_REV" ]; then
    # Loud and fatal rather than quietly checking out over somebody's tree: the
    # clone may be theirs, with work in it, and a board run against a different
    # upstream is not comparable with the one in the README either way.
    echo "setup: $LC_DIR is at $have" >&2
    echo "setup: the pin is        $LC_REV" >&2
    echo "setup: to move it:  git -C $LC_DIR fetch --depth 1 origin $LC_REV && git -C $LC_DIR checkout --detach FETCH_HEAD" >&2
    echo "setup: to measure against what is there instead:  LC_REV=$have sh judge/setup.sh" >&2
    exit 1
  fi
  echo "setup: using $LC_DIR @ $LC_REV"
fi

command -v python3 >/dev/null 2>&1 || { echo "setup: python3 is required" >&2; exit 2; }

for p in "${@:-unionfind}"; do
  echo "setup: generating test cases for $p"
  (cd "$LC_DIR" && python3 ./generate.py -p "$p")
done

echo
echo "setup: done. Now:"
echo "  MERE=<mere checkout> LC_DIR=$LC_DIR python3 judge/run.py"
